github:
  repo: https://github.com/ewbdoohyun/ewbdoohyun.github.io
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Dependencies
highlighter: "rouge"

# Permalinks
permalink: pretty

# Setup
title: Doohyun Kim
tagline: "Blog"
description: "Developer Blog"
url: http://ewbdoohyun.github.io

author:
  name: "Doohyun Kim"
  # url: https://twitter.com/sgwanlee

paginate: 5
excerpt_separator: ""
